set_property SRC_FILE_INFO {cfile:C:/Users/curra/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_1/project_1.srcs/constrs_1/new/and_gate.xdc rfile:../../../project_1.srcs/constrs_1/new/and_gate.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {A}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {B}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {C}]
